[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "web"
startCommand = "gunicorn -c gunicorn.conf.py wsgi:app"

[services.env]
PORT = "8080"