[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "web"
startCommand = "gunicorn --bind 0.0.0.0:$PORT wsgi:app"

[services.env]
PORT = "8080"